# Nombre de mi configuración
name: Node NoSQL API v1

# Eventos que detonarán el flujo de CI
on: [push]

jobs:

  # Tarea para compilar el proyecto
  build:
    # Define sobre qué sistema operativo va a compilarse el proyecto
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 # version de github actions que usaremos
      - name: Build Docker Image # nombramos este proces de build
        run: docker build . --file DockerFile --tag nosql-api-v1 # ejecutamos comandos

    # Tarea para ejecutar los tests del proyecto
  test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checout@v2
      - name: API Tests
        uses: actions/setpu-node@v1
        with: 
          node-version: '12.x'
      - run: npm ci
      - run: npm test